# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('All', 'All'), ('INFO', 'INFO'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL'), ('ERROR', 'ERROR')], max_length=5)),
                ('message', models.CharField(max_length=265)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField(default=5)),
                ('threshold', models.IntegerField(default=35)),
                ('algorithm', models.CharField(default='Mean', max_length=64)),
                ('retrospect_period', models.IntegerField(default='15')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('webapp', 'webapp'), ('temperature', 'temperature'), ('...', '...')], max_length=64)),
                ('desc', models.CharField(max_length=265)),
                ('uri', models.CharField(default='/temp/one', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sensor'),
        ),
    ]
