# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20170420_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=35)),
                ('retrospect_period', models.IntegerField(default='15')),
                ('position', models.CharField(choices=[('=', '='), ('more than', '>='), ('less than', '<=')], max_length=16)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Mail')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sensor')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(max_length=254),
        ),
    ]
