# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20170421_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='operation',
            field=models.CharField(choices=[('stop_fan', 'Stop Fan'), ('start_fan', 'Start Fan'), ('send_mail', 'Send notification')], default='stop_fan', max_length=128),
            preserve_default=False,
        ),
    ]
