# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_rule_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=16),
            preserve_default=False,
        ),
    ]
