# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_rule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('LINE', 'Line'), ('ANNOTATION', 'Annotation')], max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='position',
            field=models.CharField(choices=[('__lt__', 'less than'), ('__eq__', 'equal to'), ('__gt__', 'greater than')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=16),
        ),
    ]
