# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20170421_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('cooler', 'cooler')], max_length=64)),
                ('desc', models.CharField(max_length=265)),
                ('uri', models.CharField(default='/device/status/cooler', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Scheduler',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='ip',
            new_name='sensor_ip',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='retrospect_period',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='threshold',
        ),
        migrations.AddField(
            model_name='server',
            name='device_ip',
            field=models.GenericIPAddressField(default='192.168.10.101'),
            preserve_default=False,
        ),
    ]
